languageCode = "it"
languageName = "Italiano"
weight = 1
title = "Nuove tecnologie dell'arte"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "images/loghi/scuola NTA.png"
  description = "Biennio Arte generativa"

[params.author]
  name = "Scuola di nuove tecnologie dell'arte"
  # image = "img/blowfish_logo.png"
  headline = "Biennio Arte generativa"
  bio = "Biennio Arte generativa"
  links = [
    { instagram = "https://www.instagram.com/aba_reggiocalabria/" },
    { graduation-cap = "https://www.abarc.it/didattica/dipartimento-di-progettazione-e-arti-applicate/scuola-di-nuove-tecnologie-dellarte/biennio-arte-generativa/" },
  ]
