languageCode = "it"
languageName = "Italiano"
weight = 1
title = "Scuola di nuove tecnologie dell'arte"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Triennio Nuovi linguaggi della comunicazione"

[params.author]
  name = "Scuola di nuove tecnologie dell'arte"
  image = "img/blowfish_logo.png"
  headline = "Triennio Nuovi linguaggi della comunicazione"
  bio = "Triennio Nuovi linguaggi della comunicazione"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]