# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "DNA digitale"
pageRef = "docs"
weight = 10

[[main]]
name = "Il nostro algoritmo"
pageRef = "docs/shortcodes"
weight = 15

[[main]]
name = "Futuri Digitali"
weight = 20

[[main]]
name = "Prototipi in pixel"
parent = "Interazioni Creative"
pageRef = "examples"
weight = 30

[[main]]
name = "Echi Interattivi"
weight = 40




#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000


#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Autori"
pageRef = "authors"
weight = 20
